### PR TITLE
[fix] Update react to 0.65.1 and do not use RemoveListener on Keyboard

### PR DESCRIPTION
**Pull request by phyllipecesar**
Summary:
RemoveListener is deprecated and keeps failing for me since I updated to 0.65.2.
The error is quite clear:
```
_reactnative.keyboard.removelistener is not a function
```
(https://www.gitmemory.com/issue/react-navigation/react-navigation/9803/895419428)

See docs: https://reactnative.dev/docs/keyboard
This removeListener is deprecated

Test Plan:
Typescript + deployed in my project

### CODE REVIEW

**Comment by lucasfloriani** [comment]
@SteffeyDev can you give it a look to see if the code is ok to make the merge? I tested here and it works fine
Btw thanks for the work on the library, it's awesome \o

**Review by phyllipecesar — COMMENTED** [review]
I changed all the nits

File: src/Popover.tsx [hunk 1]
```diff
@@ -596,15 +614,27 @@ class AdaptivePopover extends Component<AdaptivePopoverProps, AdaptivePopoverSta
...
         onCloseStart={() => {
           if (onCloseStart) onCloseStart();
           this.debug('Tearing down keyboard listeners');
-          Keyboard.removeListener('keyboardDidShow', this.keyboardDidShow);
-          Keyboard.removeListener('keyboardDidHide', this.keyboardDidHide);
+          const { keyboardDidShowSubscription } = this.state;
+          // Typescript is struggling to identify `keyboardDidShowSubscription` can't be null
+          if (keyboardDidShowSubscription !== null) {
+            // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
+            (keyboardDidShowSubscription! as EmitterSubscription).remove();
```
[the remark this answers is not in the document]
Comment (SteffeyDev) [reply src/Popover.tsx]: You can try using `if (keyboardDidShowNotification)` instead of `if (keyboardDidShowNotification !== null)`, maybe TypeScript will like that better.  You could also try updating TypeScript, maybe its a bug that was fixed.

[the remark this answers is not in the document]
Comment (SteffeyDev) [reply src/Popover.tsx]: I just pulled your fork and ran `yarn tsc`, and it had to problem with that line as if.  If you remove the comments we should be good

[the remark this answers is not in the document]
Comment (phyllipecesar) [reply src/Popover.tsx]: Just removed the comments, good catch.

**Comment by SteffeyDev** [comment]
Released as 4.0.3
